version: '3.8'
services:
  postgresdb:
    image: postgres
    container_name: recipe_db
    environment:
      POSTGRES_DB: recipe_app_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: